[colors.primary]
background = "0x181616"
foreground = "0xc5c9c5"

[colors.normal]
black   = "0x0d0c0c"
blue    = "0x8ba4b0"
cyan    = "0x8ea4a2"
green   = "0x8a9a7b"
magenta = "0xa292a3"
red     = "0xc4746e"
white   = "0xC8C093"
yellow  = "0xc4b28a"

[colors.bright]
black   = "0xa6a69c"
blue    = "0x7FB4CA"
cyan    = "0x7AA89F"
green   = "0x87a987"
magenta = "0x938AA9"
red     = "0xE46876"
white   = "0xc5c9c5"
yellow  = "0xE6C384"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[[colors.indexed_colors]]
index = 16
color = "0xffa066"

[[colors.indexed_colors]]
index = 17
color = "0xff5d62"

[shell]
program = "zsh"

[cursor.style]
blinking = "Never"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[hints]
alphabet = "hutenosadigpc.r,l'"

[[hints.enabled]]
command = "firefox"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true

[[hints.enabled]]
action = "Copy"
regex = "[a-f0-9]{40}|[a-f0-9]{7,8}"

[hints.enabled.binding]
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 1.0

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 4
y = 0
