[colors.primary]
background = "0x1d2021" 
foreground = "0xd4be98" 

[colors.normal]
black   = "0x32302f" 
red     = "0xea6962" 
green   = "0xa9b665" 
yellow  = "0xd8a657" 
blue    = "0x7daea3" 
magenta = "0xd3869b" 
cyan    = "0x89b482" 
white   = "0xd4be98" 

[colors.bright]
black   = "0x32302f" 
red     = "0xea6962" 
green   = "0xa9b665" 
yellow  = "0xd8a657" 
blue    = "0x7daea3" 
magenta = "0xd3869b" 
cyan    = "0x89b482" 
white   = "0xd4be98" 

[shell]
program = "nu.exe"

[cursor.style]
blinking = "Never"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
dynamic_title = false
resize_increments = true
padding = { x = 4, y = 0 }
opacity = 1.0
