[colors.primary]
background = "0x181616"
foreground = "0xc5c9c5"

[colors.normal]
black   = "0x0d0c0c"
blue    = "0x8ba4b0"
cyan    = "0x8ea4a2"
green   = "0x8a9a7b"
magenta = "0xa292a3"
red     = "0xc4746e"
white   = "0xC8C093"
yellow  = "0xc4b28a"

[colors.bright]
black   = "0xa6a69c"
blue    = "0x7FB4CA"
cyan    = "0x7AA89F"
green   = "0x87a987"
magenta = "0x938AA9"
red     = "0xE46876"
white   = "0xc5c9c5"
yellow  = "0xE6C384"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[[colors.indexed_colors]]
index = 16
color = "0xffa066"

[[colors.indexed_colors]]
index = 17
color = "0xff5d62"

[shell]
program = "cmd.exe"
args = [
    "/k",
    "%CMDER_ROOT%\\vendor\\init.bat",
    "&&",
    "\"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat\" x64 > NUL",
]

[cursor.style]
blinking = "Never"
shape = "Block"

[env]
TERM = "xterm-256color"

# Good fonts:
# - "Terminus (TTF) for Windows
# - "FiraCode Nerd Font"
[font]
size = 12
normal = { family = "Terminus (TTF) for Windows" }

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
dynamic_title = false
resize_increments = true
padding = { x = 4, y = 0 }
opacity = 1.0
