[colors.primary]
background = "0x0d0e1c"
foreground = "0xffffff"

[colors.normal]
black   = "0x0d0c0c"
blue    = "0x79a8ff"
green   = "0x6ae4b9"
magenta = "0xb6a0ff"
red     = "0xff7f9f"
white   = "0xC8C093"
yellow  = "0xf1b090"

[shell]
program = "cmd.exe"
args = [
    "/k",
    "%CMDER_ROOT%\\vendor\\init.bat",
    "&&",
    "\"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat\" x64 > NUL",
]

[cursor.style]
blinking = "Never"
shape = "Block"

[env]
TERM = "xterm-256color"

# Good fonts:
# - "Terminus (TTF) for Windows
# - "FiraCode Nerd Font"
[font]
size = 12
normal = { family = "Terminus (TTF) for Windows" }

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
dynamic_title = false
resize_increments = true
padding = { x = 4, y = 0 }
opacity = 1.0
