[alacritty]
target_path = "~/.config/alacritty"

[bash]
target_path = "~/"

[dunst]
target_path = "~/.config/dunst"

[dwm]
target_path = "~/.config/dwm-6.2"

[emacs]
target_path = "~/.emacs.d"
is_recursive = true

[git]
target_path = "~/"

[gitui]
config_path = "git/gitui"
target_path = "~/.config/gitui"

[kitty]
target_path = "~/.config/kitty"

[latex]
target_path = "~/"

[minecraft]
target_path = "~/.local/bin"

[ncspot]
target_path = "~/.config/ncspot"

[nvim]
target_path = "~/.config/nvim"
is_recursive = true

[rofi]
target_path = "~/.config/rofi"

[rustfmt]
config_path = "rust/rustfmt"
target_path = "~/.config/rustfmt"

[sage]
target_path = "~/.sage"

[starfish]
target_path = "~/.config"

[tmux]
target_path = "~/.config/tmux"

[x]
target_path = "~/"

[zathura]
target_path = "~/.config"
is_recursive = true

[zsh]
target_path = "~/"
