[alacritty]
src = "alacritty/alacritty.toml"
target = "~/.config/alacritty"

[nushell]
target = "~/.config/nushell"

[zsh]
target = "~/"

[emacs]
target = "~/.emacs.d"
recursive = true

[git]
target = "~/.config/git"

[minecraft]
src = "minecraft/scripts"
target = "~/.local/bin"

[ncspot]
target = "~/.config/ncspot"

[nvim]
target = "~/.config/nvim"
recursive = true

[vim]
target = "~/"

[tmux]
target = "~/.config/tmux"

[tmux_scripts]
src = "tmux/scripts"
target = "~/.local/bin"

[starship]
target = "~/.config/starship"

[x]
target = "~/"

[zathura]
target = "~/.config"
recursive = true
