[wezterm]
target = "~/"

[zsh]
target = "~/"

[emacs]
target = "~/.emacs.d"
recursive = true

[git]
target = "~/.config/git"

[nvim]
target = "~/.config/nvim"
recursive = true

[vim]
target = "~/"

[vim_colors]
src = "nvim/colors/mug.vim"
target = "~/.vim/colors/mug.vim"

[vim_syntax]
src = "nvim/after/syntax"
target = "~/.vim/after/syntax"

[tmux]
target = "~/.config/tmux"

[tmux_scripts]
src = "tmux/scripts"
target = "~/.local/bin"

[x]
target = "~/"

[zathura]
target = "~/.config"
recursive = true

[gdb]
src = "gdb/.gdbinit"
target = "~/"
