[alacritty]
target = "~/.config/alacritty"

[bash]
target = "~/"

[dunst]
target = "~/.config/dunst"

[dwm]
target = "~/.config/dwm-6.2"

[emacs]
target = "~/.emacs.d"
recursive = true

[git]
target = "~/"

[gitui]
src = "git/gitui"
target = "~/.config/gitui"

[kitty]
target = "~/.config/kitty"

[latex]
target = "~/"

[minecraft]
target = "~/.local/bin"

[ncspot]
target = "~/.config/ncspot"

[nvim]
target = "~/.config/nvim"
recursive = true

[vim]
target = "~/"

[rofi]
target = "~/.config/rofi"

[rustfmt]
src = "rust/rustfmt"
target = "~/.config/rustfmt"

[sage]
target = "~/.sage"

[tmux]
target = "~/.config/tmux"

[tmux_scripts]
src = "tmux/scripts"
target = "~/.local/bin"

[starship]
target = "~/.config/starship"

[x]
target = "~/"

[zathura]
target = "~/.config"
recursive = true

[zsh]
target = "~/"

[zig]
target = "~/.config"

[clang]
target = "~/"
