[wezterm]
target = "~/"

[zsh]
target = "~/"

[emacs]
target = "~/.emacs.d"
recursive = true

[git]
target = "~/.config/git"

[nvim]
target = "~/.config/nvim"
recursive = true

[nvim_colors]
src = "vim/colors"
target = "~/.config/nvim/colors"

[nvim_syntax]
src = "vim/after/syntax"
target = "~/.config/nvim/after/syntax"

[vimrc]
src = "vim/.vimrc"
target = "~/.vimrc"

[vim_autoload]
src = "vim/autoload"
target = "~/.vim/autoload"

[vim_colors]
src = "vim/colors"
target = "~/.vim/colors"

[vim_syntax]
src = "vim/after/syntax"
target = "~/.vim/after/syntax"

[tmux]
target = "~/.config/tmux"

[tmux_scripts]
src = "tmux/scripts"
target = "~/.local/bin"

[x]
target = "~/"

[zathura]
target = "~/.config"
recursive = true

[gdb]
src = "gdb/.gdbinit"
target = "~/"
