[alacritty]
src = "alacritty/alacritty_linux.toml"
target = "~/.config/alacritty/alacritty.toml"

[wezterm]
target = "~/"

[zsh]
target = "~/"

[emacs]
target = "~/.emacs.d"
recursive = true

[git]
target = "~/.config/git"

[nvim]
target = "~/.config/nvim"
recursive = true

[vim]
target = "~/"

[tmux]
target = "~/.config/tmux"

[tmux_scripts]
src = "tmux/scripts"
target = "~/.local/bin"

[x]
target = "~/"

[zathura]
target = "~/.config"
recursive = true

[gdb]
src = "scripts/.gdbinit"
target = "~/"
