[emacs]
target = "~/.emacs.d"
recursive = true

[git]
target = "C:\\ProgramData\\Git"

[nvim]
target = "C\\Users\\luizm\\AppData\\nvim"
recursive = true

[vim]
target = "C:\\Users\\luizm\\.vim"

[rustfmt]
src = "rust\\rustfmt"
target = "C:\\Users\\luizm\\AppData\\rustfmt"

[starship]
target = "C:\\Users\\luizm\\AppData\\starship"

[powershell]
src = "powershell\\profile.ps1"
target = "C:\\Users\\luizm\\OneDrive\\Documents\\WindowsPowerShell\\Microsoft.PowerShell_profile.ps1"
