[alacritty]
target = "~/.config/alacritty"

[zsh]
target = "~/"

[bash]
target = "~/"

[dunst]
target = "~/.config/dunst"

[emacs]
target = "~/.emacs.d"
recursive = true

[git]
target = "~/.config/git"

[latex]
target = "~/"

[minecraft]
src = "minecraft/scripts"
target = "~/.local/bin"

[ncspot]
target = "~/.config/ncspot"

[nvim]
target = "~/.config/nvim"
recursive = true

[vim]
target = "~/"

[rofi]
target = "~/.config/rofi"

[tmux]
target = "~/.config/tmux"

[tmux_scripts]
src = "tmux/scripts"
target = "~/.local/bin"

[starship]
target = "~/.config/starship"

[x]
target = "~/"

[zathura]
target = "~/.config"
recursive = true
