# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt
[character] # The name of the module we are configuring is "character"
success_symbol = "[](bold purple)"
error_symbol = "[](bold red)"
vimcmd_symbol = "[](bold purple)"
