vim.keymap.set("n", "<leader>tt", function()
	require("trouble").open()
end, { desc = "[T]trouble [T]oggle" })
vim.keymap.set("n", "<leader>tw", function()
	require("trouble").open("workspace_diagnostics")
end, { desc = "[T]rouble [W]orkspace diagnostics" })
vim.keymap.set("n", "gR", function()
	require("trouble").open("lsp_references")
end)
