-- local c_like = { ".c", ".cpp", ".h", ".hpp", "*.glsl", "*.vert", "*.tesc", "*.tese", "*.geom", "*.frag", "*.comp" }
--
-- local fmt = vim.api.nvim_create_augroup("mug-fmt", { clear = true })
--
-- vim.api.nvim_create_autocmd("LspAttach", {
--     desc     = "Set autoformatter when LSP is available",
--     group    = fmt,
--     callback = function(args)
--         vim.api.nvim_create_autocmd("BufWritePre", {
--             desc     = "Autoformat buffer before saving",
--             buffer   = args.buf,
--             callback = function()
--                 vim.lsp.buf.format({ async = false, id = args.data.client_id })
--             end,
--         })
--     end,
-- })
--
-- TODO: whitespace trimmer
